---
- hosts: tomcat
  become: true
  become_user: root
#roles:
# - create_security_group
  tasks:
    - name: Install Phyton
      pip: name=docker-py version=1.7.0
  
    - name: Docker remove container 
      shell: docker rm -f restart_image 
      
    - name: Docker remove image 
      shell: docker rmi -f tomcat_image 
  
    - name: Docker build 
      shell: docker build -t tomcat_image . 
      
    - name: Restart a container
      docker_container:
        name: restart_image
        image: tomcat_image
        state: started
        restart: yes
        ports:
          - "80:8080"
        
    #- name: Docker run
    #  shell: docker run -it -d -p "80:8080" tomcat_image
    
  

  
